# Generated by Django 4.0.4 on 2022-09-25 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email_adress',
            field=models.EmailField(max_length=254),
        ),
    ]
